### ISSUE TITLE
Config error likely caused by new home assistant version

### ISSUE THREAD

**Issue by overho79** [jslove/xap_controller#11]
Hi jslove,
I've been using your custom XAP component for a couple years, and it is awesome!  My configuration has been stable for a very long time, and I have not had any issues.  All of a sudden the component is not able to load due to a configuration error.  My assumption is that it is caused by a recent home assistant upgrade...

**Error Details**
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:361
Integration: Media player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 12:26:20 PM (1 occurrences)
Last logged: 12:26:20 PM

Error while setting up xap_controller platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xap_controller/media_player.py", line 219, in setup_platform
    sourceobj = XAPSource(
                ^^^^^^^^^^
  File "/config/custom_components/xap_controller/media_player.py", line 249, in __init__
    self.parse_source(source_inputs)
  File "/config/custom_components/xap_controller/media_player.py", line 289, in parse_source
    raise Exception('Invalid Source Input config format')
Exception: Invalid Source Input config format

I've taken a look at the code, and it mentions on the branch of the if statement that it shouldn't be possible to reach it, so something strange must be going on.  I tried to setup my own devcontainer today to debug it, but have had errors getting it running so wasn't able to do so.  Any help/ideas for addressing this would be appreciated!  Thanks!

**Home Assistant Version**
Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2
Running on Raspberry PI4

**Relevant Config.yaml for my setup**

media_player:
  - platform: samsungtv_tizen
    host: 
    mac: 
  - platform: xap_controller
    path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0NCVJH-if00-port0   #Black connector USB to serial
    name: AudioMatrix
    stereo: 0 # 1 or 0, default is 0, recommend explicitly listing sterero channels
    baud: 38400 #default
    XAPType: XAP800
    zones:
      'Kyles Bath':
        - "0:1"
        - "0:2"
      'Master Closet Bath':
        - "0:3"
        - "0:4"
      'Bar and Rec Room':
        - "0:7"
        - "0:8"
      'Bonus Room':
        - "0:9"
        - "0:10"
      'Patio':
        - "1:1"
        - "1:2"
      'Upper Deck':
        - "1:3"
        - "1:4"
      'Master Bedroom':
        - "1:5"
        - "1:6"
      'Kitchen':
        - "1:7"
        - "1:8"
      'Rec Room TV Area':
        - "1:9"
        - "1:10"
      'Great Room TV Area':
        - "1:11"
        - "1:12"
    sources:
      'Sonos Player 1':
        - "0:1:O:E"
        - "0:2:P:E"
      'Sonos Player 2':
        - "0:3:Q:E"
        - "0:4:R:E"
      'Sonos Player 3':
        - "0:9:S:E"
        - "0:10:T:E"

**Comment by jslove** [comment]
I just upgraded today and didn’t notice anything but haven’t tried to use
it yet. It will be a few days before I can dig in.


Jay Love
***@***.***

**Comment by jslove** [comment]
I've just released a fix for this.

**Comment by jslove** [comment]
Fixed, thanks

**Comment by overho79** [comment]
Thank you so much Jay!  I’ll be deploying it in the next day or two when I
get home.

Cheers,

Kyle
