### ISSUE TITLE
Hassio 0.88 media_player changes

### ISSUE THREAD

**Issue by RolandWijnen** [jslove/xap_controller#3]
Hi Jay, 

I just upgraded to hassio 0.88.1. They've introduced some changes to the media_player component and some keys are not accepted anymore. I get this error:

"Sat Feb 23 2019 11:57:28 GMT+0100 (Central European Standard Time)
Your configuration contains extra keys that the platform does not support.
Please remove [name], [stereo].  (See /config/packages/media_players.yaml, line 28)."

I guess this needs to be fixed at the component level right. Where should I raise this issue so that we can still use xap_controller with the new hassio?

Cheers, Roland.

**Comment by RolandWijnen** [comment]
For the moment I left out 'name' and 'stereo = 0' (because that is the default anyway).

**Comment by jslove** [comment]
I made some updates for 0.88.  One of them is renaming the repository, but that shouldn't affect you.  But you need to change the file structure in custom_components.  You can just clone the repository into custom_components.
